In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4,5]

In [8]:
print(list1+[2])

[1, 2, 3, 4, 5, 2]


In [9]:
for i in range(len(list1)):
    list1[i] += 2

print(list1)

[3, 4, 5, 6, 7]


In [5]:
arr1 = np.array([1,2,3,4,5])

In [6]:
print(arr1+2)

[3 4 5 6 7]


In [10]:
list2 = [i for i in range(1,51)]
print(list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [11]:
list2 = list(range(1,51))
print(list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [18]:
arr2_a = np.array([[1,2,3],[4,5,6]])
arr2_b = np.array([[7,8],[9,10],[11,12]])
print(arr2_a.shape,arr2_b.shape)

(2, 3) (3, 2)


In [27]:
arr2_c = arr2_b.reshape(2,3)

In [28]:
print(arr2_c)

[[ 7  8  9]
 [10 11 12]]


In [29]:
arr3 = np.arange(11)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [30]:
a = np.array([1,2,0,0,4,0])
b = np.where(a != 0)
print(b)

(array([0, 1, 4], dtype=int64),)


In [33]:
a[4]

4

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 조건: 배열에서 5보다 큰 값의 인덱스 찾기
indices = np.where(arr > 5)

print(indices)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [38]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2],[3,4],[5,6]])
arr2_reshape = arr2.reshape(2,3)
print(arr1)
print(arr2_reshape)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [40]:
arr3 = np.array([1,2,3,4,5,6])
arr4 = np.where(arr3>3)
print(arr4)

(array([3, 4, 5], dtype=int64),)


In [41]:
arr5 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr6 = np.where(arr5 > 5)

print(arr6)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [1]:
import numpy as np

In [2]:
arr_rand = np.random.randint(1,31,size=(3,10))
print(arr_rand)

[[14  1 26  2 20 30 22 22 18 17]
 [23 11  6  2 27 25  7 27  2 23]
 [18 22 17 14 10  3 22 28 16 15]]


In [ ]:
arr_re = arr_rand.reshape(6,5)
print(arr_re)

[[14  1 26  2 20]
 [30 22 22 18 17]
 [23 11  6  2 27]
 [25  7 27  2 23]
 [18 22 17 14 10]
 [ 3 22 28 16 15]]


In [4]:
arr_idx = np.where(arr_re>15)
print(arr_idx)

(array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5], dtype=int64), array([2, 4, 0, 1, 2, 3, 4, 0, 4, 0, 2, 4, 0, 1, 2, 1, 2, 3], dtype=int64))


In [60]:
name = np.array(["영화","동원","성우","수민"])
score = np.array([[60,60],[70,70],[80,80],[90,90]])

In [ ]:
print(score)

[[60 60]
 [70 70]
 [80 80]
 [90 90]]


In [62]:
name == "운비"

array([False, False, False, False])

In [63]:
name == "영화"

array([ True, False, False, False])

In [64]:
score[name=="영화"]

array([[60, 60]])

In [65]:
arr = np.array([1,2,3,4,5])
print(arr.mean())
print(np.mean(arr))

3.0
3.0


In [ ]:
import numpy as np

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [6]:
arr2 = np.arange(50).reshape(5,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [7]:
arr2[:4,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [9]:
arr2[[2,3],[2,3]]

array([22, 33])

In [14]:
data = np.genfromtxt("./data/ratings.dat",delimiter="::",dtype="int")
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [ ]:
## 예제
#Q4 풀이 1
arr = np.array([
    [0, 1, 3, 4, 1],
    [2, 9, 8, 1, 0],
    [3, 3, 5, 9, 2],
    [2, 1, 0, 7, 8],
    [9, 8, 3, 2, 1]
])



In [ ]:
binary_loop = np.zeros_like(arr)  # arr과 같은 크기의 0 배열 생성

for i in range(arr.shape[0]):          # 행 반복
    for j in range(arr.shape[1]):      # 열 반복
        if arr[i, j] >= 8:
            binary_loop[i, j] = 1
        else:
            binary_loop[i, j] = 0

In [ ]:
# 풀이 2
binary = (arr >= 8).astype(int)

In [ ]:
# 온도 예제

temps = np.random.randint(1, 51, size=(5, 10))   
avg_temp = np.random.randint(10, 31, size=(1, 5))

temps = temps.reshape(10,5)

#요일
days = ["월", "화", "수", "목", "금"]

#Q1
#화요일 데이터
tue_values = temps[:,1]

#화요일 평균
tue_avg = avg_temp[1]

#거리계산
tue_diff = np.abs(tue_values-tue_avg)

#정렬
sort_diff = np.sort(tue_diff)

#정렬 기준 0,1번 인덱스가 가장 가까운 숫자들
d1, d2 = sort_diff[0],sort_diff[1]

# 실제값 찾기
tue_find = []
for tem in tue_values:
    if abs(tem-tue_avg) == d1 or abs(tem-tue_avg) == d2:
        tue_find.append(tem)

#화요일 아침
tue_mor = min(tue_find)
tue_aft = max(tue_find)



In [ ]:
#Q2 온도가 가장 높은 요일
max_temp = temps[0,0]
max_day_idx = 0

for day in range(5):
    for tem in range(10):
        if temps[tem,day] > max_temp:
            max_temp = temps[tem,day]
            max_day_idx = day

#가장 높은온도를 기록한 요일
print(days[max_day_idx])
#가장 높은 온도
print(max_temp)

In [ ]:
#Q3 일교차가 가장 큰 요일

#초기 계산
max_range = -1
max_range_day = 0

for day in range(5):
    day_values = temps[:,day]
    
    day_max = day_values[0]
    day_min = day_values[0]

    for tem in day_values:
        if tem > day_max:
            day_max = tem
        if tem < day_min:
            day_min = tem

    diff = day_max - day_min

    if diff > max_range:
        max_range = diff
        may_range_day = day

# 일교차가 가장 큰 요일
print(days[max_range_day])

# 일교차
print(max_range)
        

In [5]:
attendance = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, 1, 1, 0],
    [1, 1, 1, 0, 1],
    [0, 1, 0, 1, 1],
    [1, 1, 1, 1, 1]
])

# 행 = 학생
# 열 = 요일

In [12]:
# 각 학생별 출석횟수
att = []
for i in range(5):
    st = attendance[i]
    st_count = st[st!=0].size
    att.append([i,st_count])

print(att)

[[0, 5], [1, 3], [2, 4], [3, 3], [4, 5]]


In [ ]:
att = []
for i in range(5):
    st = attendance[:,i]
    st_count = st[st==0].size
    att.append([i,st_count])

print(att)

[[0, 1], [1, 1], [2, 1], [3, 1], [4, 1]]


In [15]:
att = []
for i in range(5):
    st = attendance[i]
    st_count = st[st==1].size
    if st_count == 5:
        att.append([i,st_count])

print(att)

[[0, 5], [4, 5]]
