In [1]:
import numpy as np

In [10]:
a = np.array(1)

In [13]:
print(a.dtype)

int32


In [14]:
arr1 = np.array([1, 2, 3])  # shape (3,)
arr2 = np.array([[10], [20], [30]])  # shape (3,1)

print(arr1 + arr2)  # (1,3) + (3,1) -> (3,3)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
